export type Product = {
  id: number;
  name: string;
  marketplace: string;
  marketplace_label: string;
  niche: string;
  niche_label: string;
  category: string;
  image_url?: string | null;
  product_url?: string | null;
  source: string;
  source_product_id?: string | null;
  average_price: number;
  min_price: number;
  max_price: number;
  estimated_cost: number;
  platform_fee_percent: number;
  estimated_shipping: number;
  packaging_cost: number;
  estimated_tax_percent: number;
  affiliate_commission_percent: number;
  competitors_count: number;
  search_volume: number;
  trend_score: number;
  average_rating: number;
  reviews_count: number;
  sales_velocity: number;
  return_risk: number;
  seasonality: number;
  product_weight_kg: number;
  delivery_days: number;
  supplier_reliability: number;
  visual_appeal: number;
  kit_potential: number;
  recurrence_score: number;
  created_for_demo: boolean;
};
